/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PlszMNJ8ovI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function JudgeSchedule() {
  return (<>
    <div
      className="flex items-center justify-between px-6 py-4 bg-gray-100 dark:bg-gray-800 shadow-sm">
      <div
        className="animate-fade-in-left text-xl font-semibold text-gray-800 dark:text-gray-200">
        Welcome back, John Doe
      </div>
      <div className="flex gap-4">
        <Link
          className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-gray-800 bg-white rounded-md shadow-sm hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 dark:text-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-600"
          href="#">
          View Account
        </Link>
        <Link
          className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white bg-red-500 rounded-md shadow-sm hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-700"
          href="#">
          Logout
        </Link>
      </div>
    </div>
    <div className="p-6">
      <div className="overflow-x-auto">
        <table className="w-full text-left table-auto">
          <thead className="bg-gray-100 dark:bg-gray-800">
            <tr>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">CNR Number</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Filing Number</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Filing Date</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">First Hearing</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Next Hearing</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Previous Hearing</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Stage</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Court Number</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Judge ID</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Victim Statement</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Accused Statement</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Accused ID</th>
              <th
                className="px-4 py-3 text-sm font-medium text-gray-800 dark:text-gray-200">Relevant Acts</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
            <tr>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">123456</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">ABC/2023/123</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">2023-04-01</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">2023-04-15</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">2023-05-01</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">2023-04-08</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">Pending</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">1</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">J001</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">Submitted</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">Pending</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">A001</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">IPC 302, 307</td>
            </tr>
            <tr>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">234567</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">DEF/2023/456</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">2023-03-15</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">2023-04-01</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">2023-04-22</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">2023-03-25</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">Ongoing</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">2</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">J002</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">Submitted</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">Submitted</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">A002</td>
              <td className="px-4 py-3 text-sm text-gray-800 dark:text-gray-200">IPC 323, 324</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </>);
}
